// Verilated -*- C++ -*-
// DESCRIPTION: Verilator output: Design internal header
// See Vtb_top.h for the primary calling header

#ifndef _VTB_TOP_EL2_CONFIGURABLE_GW_H_
#define _VTB_TOP_EL2_CONFIGURABLE_GW_H_  // guard

#include "verilated_heavy.h"

//==========

class Vtb_top__Syms;

//----------

VL_MODULE(Vtb_top_el2_configurable_gw) {
  public:
    
    // PORTS
    VL_IN8(rawclk,0,0);
    VL_IN8(rst_l,0,0);
    VL_IN8(gw_clk,0,0);
    VL_IN8(clken,0,0);
    VL_IN8(extintsrc_req,0,0);
    VL_IN8(meigwctrl_polarity,0,0);
    VL_IN8(meigwctrl_type,0,0);
    VL_IN8(meigwclr,0,0);
    VL_OUT8(extintsrc_req_config,0,0);
    
    // LOCAL SIGNALS
    CData/*0:0*/ __PVT__gw_int_pending;
    CData/*0:0*/ __PVT__extintsrc_req_sync;
    CData/*0:0*/ __PVT__sync_inst__DOT__din_ff1;
    
    // LOCAL VARIABLES
    CData/*0:0*/ sync_inst__DOT__sync_ff1__DOT__genblk2__DOT__dffs__DOT____Vcellinp__genblock__DOT__dffs__din;
    CData/*0:0*/ sync_inst__DOT__sync_ff2__DOT__genblk2__DOT__dffs__DOT____Vcellinp__genblock__DOT__dffs__din;
    CData/*0:0*/ int_pend_ff__DOT__genblk2__DOT__dffs__DOT____Vcellinp__genblock__DOT__dffs__din;
    
    // INTERNAL VARIABLES
  private:
    Vtb_top__Syms* __VlSymsp;  // Symbol table
  public:
    
    // CONSTRUCTORS
  private:
    VL_UNCOPYABLE(Vtb_top_el2_configurable_gw);  ///< Copying not allowed
  public:
    Vtb_top_el2_configurable_gw(const char* name = "TOP");
    ~Vtb_top_el2_configurable_gw();
    
    // INTERNAL METHODS
    void __Vconfigure(Vtb_top__Syms* symsp, bool first);
  private:
    void _ctor_var_reset() VL_ATTR_COLD;
  public:
    void _sequent__TOP__tb_top__DOT__rvtop__DOT__swerv__DOT__pic_ctrl_inst__DOT__IO_CLK_GRP__BRA__0__KET____DOT__GW__BRA__1__KET____DOT__gw_inst__32(Vtb_top__Syms* __restrict vlSymsp);
    void _sequent__TOP__tb_top__DOT__rvtop__DOT__swerv__DOT__pic_ctrl_inst__DOT__IO_CLK_GRP__BRA__0__KET____DOT__GW__BRA__2__KET____DOT__gw_inst__33(Vtb_top__Syms* __restrict vlSymsp);
    void _sequent__TOP__tb_top__DOT__rvtop__DOT__swerv__DOT__pic_ctrl_inst__DOT__IO_CLK_GRP__BRA__0__KET____DOT__GW__BRA__3__KET____DOT__gw_inst__34(Vtb_top__Syms* __restrict vlSymsp);
    void _sequent__TOP__tb_top__DOT__rvtop__DOT__swerv__DOT__pic_ctrl_inst__DOT__IO_CLK_GRP__BRA__1__KET____DOT__GW__BRA__0__KET____DOT__gw_inst__35(Vtb_top__Syms* __restrict vlSymsp);
    void _sequent__TOP__tb_top__DOT__rvtop__DOT__swerv__DOT__pic_ctrl_inst__DOT__IO_CLK_GRP__BRA__1__KET____DOT__GW__BRA__1__KET____DOT__gw_inst__36(Vtb_top__Syms* __restrict vlSymsp);
    void _sequent__TOP__tb_top__DOT__rvtop__DOT__swerv__DOT__pic_ctrl_inst__DOT__IO_CLK_GRP__BRA__1__KET____DOT__GW__BRA__2__KET____DOT__gw_inst__37(Vtb_top__Syms* __restrict vlSymsp);
    void _sequent__TOP__tb_top__DOT__rvtop__DOT__swerv__DOT__pic_ctrl_inst__DOT__IO_CLK_GRP__BRA__1__KET____DOT__GW__BRA__3__KET____DOT__gw_inst__38(Vtb_top__Syms* __restrict vlSymsp);
    void _sequent__TOP__tb_top__DOT__rvtop__DOT__swerv__DOT__pic_ctrl_inst__DOT__IO_CLK_GRP__BRA__2__KET____DOT__GW__BRA__0__KET____DOT__gw_inst__39(Vtb_top__Syms* __restrict vlSymsp);
    void _sequent__TOP__tb_top__DOT__rvtop__DOT__swerv__DOT__pic_ctrl_inst__DOT__IO_CLK_GRP__BRA__2__KET____DOT__GW__BRA__1__KET____DOT__gw_inst__40(Vtb_top__Syms* __restrict vlSymsp);
    void _sequent__TOP__tb_top__DOT__rvtop__DOT__swerv__DOT__pic_ctrl_inst__DOT__IO_CLK_GRP__BRA__2__KET____DOT__GW__BRA__2__KET____DOT__gw_inst__41(Vtb_top__Syms* __restrict vlSymsp);
    void _sequent__TOP__tb_top__DOT__rvtop__DOT__swerv__DOT__pic_ctrl_inst__DOT__IO_CLK_GRP__BRA__2__KET____DOT__GW__BRA__3__KET____DOT__gw_inst__42(Vtb_top__Syms* __restrict vlSymsp);
    void _sequent__TOP__tb_top__DOT__rvtop__DOT__swerv__DOT__pic_ctrl_inst__DOT__IO_CLK_GRP__BRA__3__KET____DOT__GW__BRA__0__KET____DOT__gw_inst__43(Vtb_top__Syms* __restrict vlSymsp);
    void _sequent__TOP__tb_top__DOT__rvtop__DOT__swerv__DOT__pic_ctrl_inst__DOT__IO_CLK_GRP__BRA__3__KET____DOT__GW__BRA__1__KET____DOT__gw_inst__44(Vtb_top__Syms* __restrict vlSymsp);
    void _sequent__TOP__tb_top__DOT__rvtop__DOT__swerv__DOT__pic_ctrl_inst__DOT__IO_CLK_GRP__BRA__3__KET____DOT__GW__BRA__2__KET____DOT__gw_inst__45(Vtb_top__Syms* __restrict vlSymsp);
    void _sequent__TOP__tb_top__DOT__rvtop__DOT__swerv__DOT__pic_ctrl_inst__DOT__IO_CLK_GRP__BRA__3__KET____DOT__GW__BRA__3__KET____DOT__gw_inst__46(Vtb_top__Syms* __restrict vlSymsp);
    void _sequent__TOP__tb_top__DOT__rvtop__DOT__swerv__DOT__pic_ctrl_inst__DOT__IO_CLK_GRP__BRA__4__KET____DOT__GW__BRA__0__KET____DOT__gw_inst__47(Vtb_top__Syms* __restrict vlSymsp);
    void _sequent__TOP__tb_top__DOT__rvtop__DOT__swerv__DOT__pic_ctrl_inst__DOT__IO_CLK_GRP__BRA__4__KET____DOT__GW__BRA__1__KET____DOT__gw_inst__48(Vtb_top__Syms* __restrict vlSymsp);
    void _sequent__TOP__tb_top__DOT__rvtop__DOT__swerv__DOT__pic_ctrl_inst__DOT__IO_CLK_GRP__BRA__4__KET____DOT__GW__BRA__2__KET____DOT__gw_inst__49(Vtb_top__Syms* __restrict vlSymsp);
    void _sequent__TOP__tb_top__DOT__rvtop__DOT__swerv__DOT__pic_ctrl_inst__DOT__IO_CLK_GRP__BRA__4__KET____DOT__GW__BRA__3__KET____DOT__gw_inst__50(Vtb_top__Syms* __restrict vlSymsp);
    void _sequent__TOP__tb_top__DOT__rvtop__DOT__swerv__DOT__pic_ctrl_inst__DOT__IO_CLK_GRP__BRA__5__KET____DOT__GW__BRA__0__KET____DOT__gw_inst__51(Vtb_top__Syms* __restrict vlSymsp);
    void _sequent__TOP__tb_top__DOT__rvtop__DOT__swerv__DOT__pic_ctrl_inst__DOT__IO_CLK_GRP__BRA__5__KET____DOT__GW__BRA__1__KET____DOT__gw_inst__52(Vtb_top__Syms* __restrict vlSymsp);
    void _sequent__TOP__tb_top__DOT__rvtop__DOT__swerv__DOT__pic_ctrl_inst__DOT__IO_CLK_GRP__BRA__5__KET____DOT__GW__BRA__2__KET____DOT__gw_inst__53(Vtb_top__Syms* __restrict vlSymsp);
    void _sequent__TOP__tb_top__DOT__rvtop__DOT__swerv__DOT__pic_ctrl_inst__DOT__IO_CLK_GRP__BRA__5__KET____DOT__GW__BRA__3__KET____DOT__gw_inst__54(Vtb_top__Syms* __restrict vlSymsp);
    void _sequent__TOP__tb_top__DOT__rvtop__DOT__swerv__DOT__pic_ctrl_inst__DOT__IO_CLK_GRP__BRA__6__KET____DOT__GW__BRA__0__KET____DOT__gw_inst__55(Vtb_top__Syms* __restrict vlSymsp);
    void _sequent__TOP__tb_top__DOT__rvtop__DOT__swerv__DOT__pic_ctrl_inst__DOT__IO_CLK_GRP__BRA__6__KET____DOT__GW__BRA__1__KET____DOT__gw_inst__56(Vtb_top__Syms* __restrict vlSymsp);
    void _sequent__TOP__tb_top__DOT__rvtop__DOT__swerv__DOT__pic_ctrl_inst__DOT__IO_CLK_GRP__BRA__6__KET____DOT__GW__BRA__2__KET____DOT__gw_inst__57(Vtb_top__Syms* __restrict vlSymsp);
    void _sequent__TOP__tb_top__DOT__rvtop__DOT__swerv__DOT__pic_ctrl_inst__DOT__IO_CLK_GRP__BRA__6__KET____DOT__GW__BRA__3__KET____DOT__gw_inst__58(Vtb_top__Syms* __restrict vlSymsp);
    void _sequent__TOP__tb_top__DOT__rvtop__DOT__swerv__DOT__pic_ctrl_inst__DOT__IO_CLK_GRP__BRA__7__KET____DOT__GW__BRA__0__KET____DOT__gw_inst__59(Vtb_top__Syms* __restrict vlSymsp);
    void _sequent__TOP__tb_top__DOT__rvtop__DOT__swerv__DOT__pic_ctrl_inst__DOT__IO_CLK_GRP__BRA__7__KET____DOT__GW__BRA__1__KET____DOT__gw_inst__60(Vtb_top__Syms* __restrict vlSymsp);
    void _sequent__TOP__tb_top__DOT__rvtop__DOT__swerv__DOT__pic_ctrl_inst__DOT__IO_CLK_GRP__BRA__7__KET____DOT__GW__BRA__2__KET____DOT__gw_inst__61(Vtb_top__Syms* __restrict vlSymsp);
    void _sequent__TOP__tb_top__DOT__rvtop__DOT__swerv__DOT__pic_ctrl_inst__DOT__IO_CLK_GRP__BRA__7__KET____DOT__GW__BRA__3__KET____DOT__gw_inst__62(Vtb_top__Syms* __restrict vlSymsp);
    void _settle__TOP__tb_top__DOT__rvtop__DOT__swerv__DOT__pic_ctrl_inst__DOT__IO_CLK_GRP__BRA__0__KET____DOT__GW__BRA__1__KET____DOT__gw_inst__1(Vtb_top__Syms* __restrict vlSymsp) VL_ATTR_COLD;
    void _settle__TOP__tb_top__DOT__rvtop__DOT__swerv__DOT__pic_ctrl_inst__DOT__IO_CLK_GRP__BRA__0__KET____DOT__GW__BRA__2__KET____DOT__gw_inst__2(Vtb_top__Syms* __restrict vlSymsp) VL_ATTR_COLD;
    void _settle__TOP__tb_top__DOT__rvtop__DOT__swerv__DOT__pic_ctrl_inst__DOT__IO_CLK_GRP__BRA__0__KET____DOT__GW__BRA__3__KET____DOT__gw_inst__3(Vtb_top__Syms* __restrict vlSymsp) VL_ATTR_COLD;
    void _settle__TOP__tb_top__DOT__rvtop__DOT__swerv__DOT__pic_ctrl_inst__DOT__IO_CLK_GRP__BRA__1__KET____DOT__GW__BRA__0__KET____DOT__gw_inst__4(Vtb_top__Syms* __restrict vlSymsp) VL_ATTR_COLD;
    void _settle__TOP__tb_top__DOT__rvtop__DOT__swerv__DOT__pic_ctrl_inst__DOT__IO_CLK_GRP__BRA__1__KET____DOT__GW__BRA__1__KET____DOT__gw_inst__5(Vtb_top__Syms* __restrict vlSymsp) VL_ATTR_COLD;
    void _settle__TOP__tb_top__DOT__rvtop__DOT__swerv__DOT__pic_ctrl_inst__DOT__IO_CLK_GRP__BRA__1__KET____DOT__GW__BRA__2__KET____DOT__gw_inst__6(Vtb_top__Syms* __restrict vlSymsp) VL_ATTR_COLD;
    void _settle__TOP__tb_top__DOT__rvtop__DOT__swerv__DOT__pic_ctrl_inst__DOT__IO_CLK_GRP__BRA__1__KET____DOT__GW__BRA__3__KET____DOT__gw_inst__7(Vtb_top__Syms* __restrict vlSymsp) VL_ATTR_COLD;
    void _settle__TOP__tb_top__DOT__rvtop__DOT__swerv__DOT__pic_ctrl_inst__DOT__IO_CLK_GRP__BRA__2__KET____DOT__GW__BRA__0__KET____DOT__gw_inst__8(Vtb_top__Syms* __restrict vlSymsp) VL_ATTR_COLD;
    void _settle__TOP__tb_top__DOT__rvtop__DOT__swerv__DOT__pic_ctrl_inst__DOT__IO_CLK_GRP__BRA__2__KET____DOT__GW__BRA__1__KET____DOT__gw_inst__9(Vtb_top__Syms* __restrict vlSymsp) VL_ATTR_COLD;
    void _settle__TOP__tb_top__DOT__rvtop__DOT__swerv__DOT__pic_ctrl_inst__DOT__IO_CLK_GRP__BRA__2__KET____DOT__GW__BRA__2__KET____DOT__gw_inst__10(Vtb_top__Syms* __restrict vlSymsp) VL_ATTR_COLD;
    void _settle__TOP__tb_top__DOT__rvtop__DOT__swerv__DOT__pic_ctrl_inst__DOT__IO_CLK_GRP__BRA__2__KET____DOT__GW__BRA__3__KET____DOT__gw_inst__11(Vtb_top__Syms* __restrict vlSymsp) VL_ATTR_COLD;
    void _settle__TOP__tb_top__DOT__rvtop__DOT__swerv__DOT__pic_ctrl_inst__DOT__IO_CLK_GRP__BRA__3__KET____DOT__GW__BRA__0__KET____DOT__gw_inst__12(Vtb_top__Syms* __restrict vlSymsp) VL_ATTR_COLD;
    void _settle__TOP__tb_top__DOT__rvtop__DOT__swerv__DOT__pic_ctrl_inst__DOT__IO_CLK_GRP__BRA__3__KET____DOT__GW__BRA__1__KET____DOT__gw_inst__13(Vtb_top__Syms* __restrict vlSymsp) VL_ATTR_COLD;
    void _settle__TOP__tb_top__DOT__rvtop__DOT__swerv__DOT__pic_ctrl_inst__DOT__IO_CLK_GRP__BRA__3__KET____DOT__GW__BRA__2__KET____DOT__gw_inst__14(Vtb_top__Syms* __restrict vlSymsp) VL_ATTR_COLD;
    void _settle__TOP__tb_top__DOT__rvtop__DOT__swerv__DOT__pic_ctrl_inst__DOT__IO_CLK_GRP__BRA__3__KET____DOT__GW__BRA__3__KET____DOT__gw_inst__15(Vtb_top__Syms* __restrict vlSymsp) VL_ATTR_COLD;
    void _settle__TOP__tb_top__DOT__rvtop__DOT__swerv__DOT__pic_ctrl_inst__DOT__IO_CLK_GRP__BRA__4__KET____DOT__GW__BRA__0__KET____DOT__gw_inst__16(Vtb_top__Syms* __restrict vlSymsp) VL_ATTR_COLD;
    void _settle__TOP__tb_top__DOT__rvtop__DOT__swerv__DOT__pic_ctrl_inst__DOT__IO_CLK_GRP__BRA__4__KET____DOT__GW__BRA__1__KET____DOT__gw_inst__17(Vtb_top__Syms* __restrict vlSymsp) VL_ATTR_COLD;
    void _settle__TOP__tb_top__DOT__rvtop__DOT__swerv__DOT__pic_ctrl_inst__DOT__IO_CLK_GRP__BRA__4__KET____DOT__GW__BRA__2__KET____DOT__gw_inst__18(Vtb_top__Syms* __restrict vlSymsp) VL_ATTR_COLD;
    void _settle__TOP__tb_top__DOT__rvtop__DOT__swerv__DOT__pic_ctrl_inst__DOT__IO_CLK_GRP__BRA__4__KET____DOT__GW__BRA__3__KET____DOT__gw_inst__19(Vtb_top__Syms* __restrict vlSymsp) VL_ATTR_COLD;
    void _settle__TOP__tb_top__DOT__rvtop__DOT__swerv__DOT__pic_ctrl_inst__DOT__IO_CLK_GRP__BRA__5__KET____DOT__GW__BRA__0__KET____DOT__gw_inst__20(Vtb_top__Syms* __restrict vlSymsp) VL_ATTR_COLD;
    void _settle__TOP__tb_top__DOT__rvtop__DOT__swerv__DOT__pic_ctrl_inst__DOT__IO_CLK_GRP__BRA__5__KET____DOT__GW__BRA__1__KET____DOT__gw_inst__21(Vtb_top__Syms* __restrict vlSymsp) VL_ATTR_COLD;
    void _settle__TOP__tb_top__DOT__rvtop__DOT__swerv__DOT__pic_ctrl_inst__DOT__IO_CLK_GRP__BRA__5__KET____DOT__GW__BRA__2__KET____DOT__gw_inst__22(Vtb_top__Syms* __restrict vlSymsp) VL_ATTR_COLD;
    void _settle__TOP__tb_top__DOT__rvtop__DOT__swerv__DOT__pic_ctrl_inst__DOT__IO_CLK_GRP__BRA__5__KET____DOT__GW__BRA__3__KET____DOT__gw_inst__23(Vtb_top__Syms* __restrict vlSymsp) VL_ATTR_COLD;
    void _settle__TOP__tb_top__DOT__rvtop__DOT__swerv__DOT__pic_ctrl_inst__DOT__IO_CLK_GRP__BRA__6__KET____DOT__GW__BRA__0__KET____DOT__gw_inst__24(Vtb_top__Syms* __restrict vlSymsp) VL_ATTR_COLD;
    void _settle__TOP__tb_top__DOT__rvtop__DOT__swerv__DOT__pic_ctrl_inst__DOT__IO_CLK_GRP__BRA__6__KET____DOT__GW__BRA__1__KET____DOT__gw_inst__25(Vtb_top__Syms* __restrict vlSymsp) VL_ATTR_COLD;
    void _settle__TOP__tb_top__DOT__rvtop__DOT__swerv__DOT__pic_ctrl_inst__DOT__IO_CLK_GRP__BRA__6__KET____DOT__GW__BRA__2__KET____DOT__gw_inst__26(Vtb_top__Syms* __restrict vlSymsp) VL_ATTR_COLD;
    void _settle__TOP__tb_top__DOT__rvtop__DOT__swerv__DOT__pic_ctrl_inst__DOT__IO_CLK_GRP__BRA__6__KET____DOT__GW__BRA__3__KET____DOT__gw_inst__27(Vtb_top__Syms* __restrict vlSymsp) VL_ATTR_COLD;
    void _settle__TOP__tb_top__DOT__rvtop__DOT__swerv__DOT__pic_ctrl_inst__DOT__IO_CLK_GRP__BRA__7__KET____DOT__GW__BRA__0__KET____DOT__gw_inst__28(Vtb_top__Syms* __restrict vlSymsp) VL_ATTR_COLD;
    void _settle__TOP__tb_top__DOT__rvtop__DOT__swerv__DOT__pic_ctrl_inst__DOT__IO_CLK_GRP__BRA__7__KET____DOT__GW__BRA__1__KET____DOT__gw_inst__29(Vtb_top__Syms* __restrict vlSymsp) VL_ATTR_COLD;
    void _settle__TOP__tb_top__DOT__rvtop__DOT__swerv__DOT__pic_ctrl_inst__DOT__IO_CLK_GRP__BRA__7__KET____DOT__GW__BRA__2__KET____DOT__gw_inst__30(Vtb_top__Syms* __restrict vlSymsp) VL_ATTR_COLD;
    void _settle__TOP__tb_top__DOT__rvtop__DOT__swerv__DOT__pic_ctrl_inst__DOT__IO_CLK_GRP__BRA__7__KET____DOT__GW__BRA__3__KET____DOT__gw_inst__31(Vtb_top__Syms* __restrict vlSymsp) VL_ATTR_COLD;
} VL_ATTR_ALIGNED(VL_CACHE_LINE_BYTES);

//----------


#endif  // guard
